Step 7: Creating Contact Me Section
leehaney254/myportfolio pull request #6
Opened 2022-11-01 09:26 UTC by leehaney254

## Step 7: Creating Contact Me Section
In this step I:
- Added contact Me section
- Linked my form to formspree
- updated my readme.md file

2022-11-01 15:56 UTC, jerryowusu requested changes
Hi @Team

Good job so far!
Your project is looking fantastic :star_struck: 

However, I've found some room for improvement that can help you accomplish a more readable/clean code and make your project look professional :sunglasses:

![so-close](https://user-images.githubusercontent.com/65233860/199277547-33acf372-505a-4c19-bd4e-1cbe3aba3664.gif)


## Highlights
All linters are passing :heavy_check_mark: 
Good commit messages :heavy_check_mark: 
Excellent pull request title and descriptive summary :1st_place_medal: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- [x] Your readme documentation lacks a good description and a license reference. Remember, a good documentation not only make your project looks professional, it is also a testament as to how discipline and committed you are to your work. :hammer_and_wrench:  Kindly check and fix that accordingly.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-01 15:56 UTC, jerryowusu commented on styles.css
> +}
Kindly stick to the design as much as possible. There are some disparities between your design and that of the figma especially with regards to the spacing and positioning. There is a blank space to the right side which increases with increasing screen width as shown below. :1234: Kindly check and fix that.

Your design            |  The design template
:-------------------------:|:-------------------------:
![Screenshot from 2022-11-01 15-46-31](https://user-images.githubusercontent.com/65233860/199276106-c26a7a47-acfb-4f72-ba26-1254b15b4ded.png)  |  ![Screenshot from 2022-11-01 15-46-42](https://user-images.githubusercontent.com/65233860/199276137-676b2d2b-6657-4cf9-aade-0b0297250027.png)

2022-11-01 15:56 UTC, jerryowusu commented on styles.css
>    border: 1px solid #f55800;
The button interactions such as hover, active enable etc is not working for the form button, kindly check and fix that. :pray:

2022-11-02 08:29 UTC, leehaney254 commented
Hello!
- I have updated my readme file. :smile: 
- Hover is working on the form button. :100: 
- There are no white spaces growing. :+1:

2022-11-02 08:46 UTC, Olamarx approved these changes
Hi @leehaney254, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights
- Linters passed ✔️ 
- Descriptive commit messages 👍🏼 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-02 08:54 UTC, merged

2022-11-03 07:17 UTC, Talha-Hanif5666 reviewed
**Hi @Talha-Hanif5666,**
![157397398-00904e26-60ec-46cd-9510-240661c250ef](https://user-images.githubusercontent.com/114238556/199665066-d28ce829-9a6d-4239-a8ad-54b49c5cce0d.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



**Highlights**
 No linters errors :heavy_check_mark:
 Descriptive PR :heavy_check_mark:
Good commit messages :heavy_check_mark:

**Changes Required** :recycle: 
 Please kindly check the comments under the review point_down point_down
**Optional suggestions**
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

2022-11-03 07:17 UTC, Talha-Hanif5666 commented on index.html
>      />
I think it is better to close the link tag in the same line on which you ended the text.  Kindly, please move "/>" to the previous line i-e line#11.  By doing this, your code will look more professional.

2022-11-03 07:19 UTC, Rana-Mudassir commented
Everything is perfect. Linters are checked. The formatting is good. The code is clean to go.
Cheers and Happy coding!👏👏👏

2022-11-03 07:22 UTC, Lucas-Erkana reviewed
Hi @leehaney254 
our project is complete! There is nothing else to say other than... Great job 👏
Congratulations! 🎉

TO HIGHLIGHT:

Great job Implementing the changes provided by the previous reviewers ✅
Your project is professional ✅
Your repo is professional ✅
Well structured files ✅
No Linter errors ✅
![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966](https://user-images.githubusercontent.com/41428579/199665746-1875ecb3-30ff-42fc-b447-89ad8fb907a9.gif)

[OPTIONAL] I suggest adding the MIT.md file to your project 👌, Here is the [Micorverse Template](https://github.com/microverseinc/readme-template/blob/master/MIT.md), and remember to customize it 😉
he MIT license gives users express permission to reuse code for any purpose, sometimes even if the code is part of proprietary software. As long as users include the original copy of the MIT license in their distribution, they can make any changes or modifications to the code to suit their own needs. 💯
very comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Cheers and Happy coding!👏👏👏