Step 7: Creating a desktop version
leehaney254/myportfolio pull request #8
Opened 2022-11-04 10:30 UTC by leehaney254

## Step 7: Creating a desktop version
In this step I:
- Created different sections of the desktop version
- Modified different CSS styles
- Modified readme.

2022-11-04 12:00 UTC, anagudelogu requested changes
Hi @leehaney254, 

Great job working on the responsive version of your portfolio! 🍾 🎆 
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/nYYtQdLqwwlTe3ccKh/giphy.gif"/>

## Highlights
✅ Great use of GitHub flow. 💯 
✅ Descriptive commit messages. 💬 
✅ Professional PR title and summary. 🥇 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-04 12:00 UTC, anagudelogu commented on index.html
>    <body>
- [ ] Great job working on the responsiveness of your project! 💯 However, there are still some things you can improve in order to make that responsiveness smooth. 🤓 After the breakpoint, some sections are getting a blank space on the right, so people that use 769px~1100px devices to browse your page will have this visual bug. Please work on it! 🤓 🛠️ 

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/77069011/199962321-9f32ea52-43be-4ca4-8614-21498ca8fbb6.gif)

2022-11-04 12:00 UTC, anagudelogu commented on index.html
> +        </div>
- [x] While you did a great job following the Figma template 🎨 there are still some details missing, such as the correct font family, and the height of the section! Please fix those. 🤓 🛠️ 

|Template (1440px)|Your design (1440px)|
|---|---|
| ![image](https://user-images.githubusercontent.com/77069011/199964525-4b61e7d3-b98a-456e-ac5e-184b38501d27.png) | ![imageedit_4_3038701028](https://user-images.githubusercontent.com/77069011/199964382-1e79debc-8667-421b-b01d-35d2e6bfcded.gif) |

2022-11-04 12:00 UTC, anagudelogu commented on index.html
> +        <div id="recent-rule">
- [x] Overall this section is looking really good! 👍🏼 It would be a good idea to fix the space between the featured project from the rest of the cards and the size of the title! 🤓 🛠️ 

|Template|Your design|
|---|---|
| ![image](https://user-images.githubusercontent.com/77069011/199965884-e3e2d175-e70e-4e91-81c4-a0ac2371c727.png) | ![imageedit_6_5229374530](https://user-images.githubusercontent.com/77069011/199965639-e0901071-ffae-4cf7-92f5-1cf69f46726b.gif) |

2022-11-04 12:00 UTC, anagudelogu commented on index.html
> +        </p>
- [x] Let's try to stick as much as possible to the given Figma design 🎨. Please fix the social media footer to match the design and also correct the color, text-align, and font weight of the paragraph! 🤓 🛠️ 


|Template|Your design|
|---|---|
| ![image](https://user-images.githubusercontent.com/77069011/199966847-a40569ff-0ff8-4f34-941a-1909d462fe2e.png) | ![imageedit_9_8777336161](https://user-images.githubusercontent.com/77069011/199966759-7c164073-3bc0-4dec-9a43-0c7372c939ac.gif) |

2022-11-04 12:00 UTC, anagudelogu commented on styles.css
> +#large-image {
- [x] I noticed that you have multiple repeated CSS properties across your stylesheet. It would be great if you can find a way of reducing this duplication of code ♻️. Remember that not repeating pieces of code will keep your codebase clean and readable. 🤓 🛠️ 

There are multiple ways of achieving this, one of them is creating a class `"flex"`:

```CSS
.flex {
  display: flex;
}
``` 

And then, use it in your HTML elements where you need a flex container:

```HTML
<div class="flex"> This is a flex container </div>
```

Please, consider fixing this! 🤓

2022-11-04 19:48 UTC, leehaney254 commented on index.html
> +        </p>
I have fixed it. Thank you. :smile:

2022-11-04 20:01 UTC, leehaney254 commented on index.html
> +        <div id="recent-rule">
I have fixed the spaces between and the title size. :muscle:

2022-11-04 20:25 UTC, leehaney254 commented on index.html
> +        </div>
I have fixed the font family and height section. Thank you. :+1:

2022-11-04 20:57 UTC, leehaney254 commented on styles.css
> +#large-image {
I have reduced the repeating elements as much as possible without braking my code. Thank you for the suggestion. :+1:

2022-11-04 20:58 UTC, leehaney254 commented on index.html
>    <body>
I have fixed the white spaces. Thank you. :muscle:

2022-11-04 21:28 UTC, bienvenuushindi requested changes
### Hi @leehaney254 ,

Good job implementing most of the requested changes!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- GitHub flow is used correctly. ✔
- All linter checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-11-04 21:28 UTC, bienvenuushindi commented on index.html
> +        <div id="recent-rule">
:red_circle:  I think you are almost there. You still have this required change to implement. As requested by the previous reviewer, please make sure you add the space between the featured project and the section under it. I think you can increase the bottom  margin of this block   `<div id="recent-rule">`

Your Design
![moreroom](https://user-images.githubusercontent.com/26736582/200077279-b00ed798-60bf-4e43-a80d-f22a7184cf3b.png)

Figma Design
<img src="https://user-images.githubusercontent.com/77069011/199965884-e3e2d175-e70e-4e91-81c4-a0ac2371c727.png">

2022-11-05 08:04 UTC, leehaney254 commented
Thank you very much. I have made the changes as suggested. :muscle:

2022-11-05 08:36 UTC, franclobo approved these changes
Hi @leehaney254, 

# STATUS: APPROVED 😃 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- No linter errors ✔️ 
- Correct Github flow ✅ 
- Descriptive PR ☑️ 
- Professional README file 💯

## Optional suggestions

- [ ] **[OPTIONAL]** Please fix the width of the text to be similar to the Figma template 👇🏽

| Figma template | Your design |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/200110649-21fce593-c916-4dfd-b55b-988e3708de9f.png) | ![image](https://user-images.githubusercontent.com/58642949/200110673-eb9fe612-af54-4cf8-86e3-b68078e2e085.png) |

- [ ] **[OPTIONAL]** The first code reviewer said you, but the last didn't remind you. Kindly use the **correct color, text alignment, and font weight of the paragraph** to be similar to the Figma template 👇🏽 

> Let's try to stick as much as possible to the given Figma design 🎨. Please fix the social media footer to match the design and also correct the color, text-align, and font weight of the paragraph! 🤓 🛠️

| Figma template | Your design |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/200110690-998fc830-040a-447d-9434-0e461d12d875.png) | ![image](https://user-images.githubusercontent.com/58642949/200110705-286b7290-d867-4610-a9df-9134759b13e0.png) |

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-05 09:31 UTC, merged